Repository GFGRBU/Web-Development-3.0, pull requests merged in 2024-10, with the labels that each got.

#3 Created Projects
  Calculator App/README.md
  E-Commerce Product Page/README.md
  Personal Portfolio Website/README.md
  Quiz App/README.md
  Responsive Blog Page/README.md
  To-Do List Application/README.md
  Weather App/README.md
Labels: hacktoberfest-accepted

#7 made basic calculator app with almost all features mentioned in .md
  Calculator App/calculator/.gitignore
  Calculator App/calculator/README.md
  Calculator App/calculator/eslint.config.js
  Calculator App/calculator/index.html
  Calculator App/calculator/package-lock.json
  Calculator App/calculator/package.json
  Calculator App/calculator/public/vite.svg
  Calculator App/calculator/src/App.css
  Calculator App/calculator/src/App.jsx
  Calculator App/calculator/src/assets/react.svg
  Calculator App/calculator/src/index.css
  Calculator App/calculator/src/main.jsx
  Calculator App/calculator/vite.config.js
Labels: hacktoberfest-accepted

#9 Implemented the To-Do list Application using Flask as a Backend
  To-Do List Application/solution-akshat0824/README.md
  To-Do List Application/solution-akshat0824/app.py
  To-Do List Application/solution-akshat0824/templates/edit.html
  To-Do List Application/solution-akshat0824/templates/index.html
Labels: hactoberfest, hacktoberfest-accepted, frontend

#25 weather-appp
  WeatherApp/src/Weather.js
Labels: hactoberfest, hacktoberfest-accepted

#29 Responsive blog page branch
  E-Commerce Product Page/app.js
  E-Commerce Product Page/index.html
  E-Commerce Product Page/style.css
  Movie Search App/app.py
  Movie Search App/index.html
  Movie Search App/script.js
  Movie Search App/style.css
  Quiz App/app.js
  Quiz App/index.html
  Quiz App/style.css
  Responsive Blog Page/index.html
  Responsive Blog Page/style.css
  To-Do List Application/index.html
  To-Do List Application/script.jss
  To-Do List Application/style.css
Labels: hactoberfest, hacktoberfest-accepted

#31 Add real time chat application
  Real-time Chat Application/.gitignore
  Real-time Chat Application/README.md
  Real-time Chat Application/api/.gitignore
  Real-time Chat Application/api/index.js
  Real-time Chat Application/api/package-lock.json
  Real-time Chat Application/api/package.json
  Real-time Chat Application/client/.gitignore
  Real-time Chat Application/client/package-lock.json
  Real-time Chat Application/client/package.json
  Real-time Chat Application/client/public/index.html
  Real-time Chat Application/client/src/App.css
  Real-time Chat Application/client/src/App.js
  Real-time Chat Application/client/src/Chat.js
  Real-time Chat Application/client/src/index.js
  Real-time Chat Application/package-lock.json
  Real-time Chat Application/package.json
Labels: hactoberfest, hacktoberfest-accepted

#32 added javascript mini project calculator
  jsminiprojects/Calculator/index.html
  jsminiprojects/Calculator/index.js
  jsminiprojects/Calculator/styles.css
Labels: good first issue, hactoberfest, hacktoberfest-accepted

#33 added javascript mini project weather app
  jsminiprojects/Weather/assets/clear.png
  jsminiprojects/Weather/assets/clouds.png
  jsminiprojects/Weather/assets/drizzle.png
  jsminiprojects/Weather/assets/heavy-rain.png
  jsminiprojects/Weather/assets/humidity.png
  jsminiprojects/Weather/assets/mist.png
  jsminiprojects/Weather/assets/partly-cloud.png
  jsminiprojects/Weather/assets/rain.png
  jsminiprojects/Weather/assets/search.png
  jsminiprojects/Weather/assets/snow.png
  jsminiprojects/Weather/assets/sunny.png
  jsminiprojects/Weather/assets/wind.png
  jsminiprojects/Weather/assets/windy.png
  jsminiprojects/Weather/index.html
  jsminiprojects/Weather/index.js
  jsminiprojects/Weather/styles.css
Labels: good first issue, hactoberfest, hacktoberfest-accepted

#38 Text change
  Responsive Blog Page/index.html
Labels: good first issue, hactoberfest, hacktoberfest-accepted
